services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080" # Expose frontend app on port 8080
    environment:
      - VITE_API_URL=/api  # Configure API endpoint
    volumes:
      - ./.env:/app/.env:ro  # Mount root .env file
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./backend
    # Remove port 80 exposure if not needed externally
    environment:
      # Database connection settings
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy # Ensure DB starts first
    volumes:
      - ./backend:/var/www/html # Mount backend code
      - ./.env:/var/www/html/.env:ro  # Mount root .env file

  db:
    image: mariadb:latest
    environment:
      # Database credentials from .env
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql # Persist database
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # Init script
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mariadb", "-u${DB_USER}", "-p${DB_PASSWORD}", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge

volumes:
  db_data: